export default function HowItWorks() {
  return (
    <section className="mx-auto mt-14 md:mt-20 mb-28 max-w-[calc(806px+32px)] px-4 text-center">
      <h3 className="font-unbounded text-lg font-medium">How it works</h3>
      <div className="mt-8 flex flex-col items-center gap-5">
        <div className="rounded-[60px] border border-1 border-[#FFFFFF30]  w-full">
          <p className="font-manrope font-light text-base md:text-md-small py-3">
            Input keywords and preferences to kickstart the creative process.
          </p>
        </div>
        <div className="h-10 w-[1px] bg-[#FFFFFF30]" />
        <div className="rounded-[60px] border border-1 border-[#FFFFFF30]  w-full">
          <p className="font-manrope font-light text-base md:text-md-small py-3">
            Discover a wide variety of name suggestions generated by our AI
            algorithms.
          </p>
        </div>
        <div className="h-10 w-[1px] bg-[#FFFFFF30]" />
        <div className="rounded-[60px] border border-1 border-[#FFFFFF30]  w-full">
          <p className="font-manrope font-light text-base md:text-md-small py-3">
            Every generated name is simultaneously checked in domain registers
            for availability.
          </p>
        </div>
        <div className="h-10 w-[1px] bg-[#FFFFFF30]" />
        <div className="rounded-[60px] border border-1 border-[#FFFFFF30]  w-full">
          <p className="font-manrope font-light text-base md:text-md-small py-3">
            Refine your search by updating the inputed preference.
          </p>
        </div>
        <div className="h-10 w-[1px] bg-[#FFFFFF30]" />
        <div className="rounded-[60px] border border-1 border-[#FFFFFF30]  w-full">
          <p className="font-manrope font-light text-base md:text-md-small py-3">
            Save your favourite names for further consideration or proceed to
            buy the domain.
          </p>
        </div>
      </div>
    </section>
  );
}
