import {Unbounded, Manrope} from 'next/font/google';
import '@/styles/globals.css';
import '@/styles/react-select.css';
import {DataProvider, QueryProvider, UserProvider} from '@/context';

const unbounded = Unbounded({
  variable: '--font-unbounded',
  subsets: ['latin'],
  display: 'swap',
});

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={`${unbounded.variable} ${manrope.variable}`}>
        <QueryProvider>
          <UserProvider>
            <DataProvider>{children}</DataProvider>
          </UserProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
