import {manrope, unbounded} from '@/assets/fonts';
import '@/styles/globals.css';
import '@/styles/react-select.css';
import {
  DataProvider,
  QueryProvider,
  SelectedOptionsProvider,
  UserProvider,
} from '@/context';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={`${unbounded.variable} ${manrope.variable}`}>
        <QueryProvider>
          <UserProvider>
            <DataProvider>
              <SelectedOptionsProvider>{children}</SelectedOptionsProvider>
            </DataProvider>
          </UserProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
